import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { lookup } from "node:dns/promises";
import { request as httpsRequest } from "node:https";
import { join } from "node:path";
import { isIP } from "node:net";
const fail=code=>{throw new Error(code);};
const plain=v=>v!==null&&typeof v==="object"&&!Array.isArray(v)&&Object.getPrototypeOf(v)===Object.prototype;
export function validateToolchainLock(lock){if(!plain(lock)||lock.name!=="aca-verifier-toolchain"||lock.lockfileVersion!==3||!plain(lock.packages)||!plain(lock.packages[""]))fail("TOOLCHAIN_LOCK_REFUSED");const root=lock.packages[""];if(root.name!=="aca-verifier-toolchain"||!plain(root.devDependencies))fail("TOOLCHAIN_LOCK_REFUSED");for(const version of Object.values(root.devDependencies))if(typeof version!=="string"||!/^[0-9]+\.[0-9]+\.[0-9]+(?:-[0-9A-Za-z.-]+)?$/.test(version))fail("TOOLCHAIN_LOCK_REFUSED");const rows=[];for(const [path,row] of Object.entries(lock.packages)){if(path==="")continue;if(!path.startsWith("node_modules/")||!plain(row)||typeof row.version!=="string"||typeof row.resolved!=="string"||typeof row.integrity!=="string"||!/^sha512-[A-Za-z0-9+/]+={0,2}$/.test(row.integrity))fail("TOOLCHAIN_LOCK_REFUSED");let url;try{url=new URL(row.resolved);}catch{fail("TOOLCHAIN_LOCK_REFUSED");}if(url.protocol!=="https:"||url.hostname!=="registry.npmjs.org"||url.port||url.username||url.password||url.search||url.hash)fail("TOOLCHAIN_LOCK_REFUSED");rows.push(Object.freeze({path,version:row.version,url:url.href,integrity:row.integrity}));}if(rows.length===0)fail("TOOLCHAIN_LOCK_REFUSED");for(const [name,version] of Object.entries(root.devDependencies)){const row=lock.packages[`node_modules/${name}`];if(!row||row.version!==version)fail("TOOLCHAIN_LOCK_REFUSED");}return Object.freeze(rows);}
const v4=n=>n.split(".").map(Number);
export function isPublicAddress(value){const kind=isIP(value);if(kind===4){const [a,b]=v4(value);return !(a===0||a===10||a===127||a>=224||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168)||(a===100&&b>=64&&b<=127)||(a===198&&(b===18||b===19)));}if(kind===6){const s=value.toLowerCase();return !(s==="::"||s==="::1"||s.startsWith("fc")||s.startsWith("fd")||s.startsWith("fe8")||s.startsWith("fe9")||s.startsWith("fea")||s.startsWith("feb")||s.startsWith("ff")||s.startsWith("::ffff:127."));}return false;}
export async function prepareTarballDirectory(lock,directory,io){await mkdir(directory,{recursive:true,mode:0o700});const stored=[];const receipt=await fetchVerifiedToolchain(lock,{...io,store:async(row,bytes,artifact)=>{const fileName=`${artifact.digest}.tgz`;await writeFile(join(directory,fileName),bytes,{mode:0o400,flag:"wx"});stored.push({...artifact,fileName});}});return Object.freeze({schema:"aca-toolchain-preparation/v1",destinations:receipt.destinations,artifacts:Object.freeze(stored)});}
export function createPinnedHttpsIO(){return{async resolve(hostname){return(await lookup(hostname,{all:true,verbatim:true})).map(row=>row.address)},fetch(request){return new Promise((resolve,reject)=>{const url=new URL(request.url);const req=httpsRequest({protocol:"https:",hostname:url.hostname,port:443,path:url.pathname,method:"GET",servername:url.hostname,rejectUnauthorized:true,agent:false,headers:{host:url.hostname,"user-agent":"WorkHub-ACA-Toolchain/1"},lookup:(_host,options,callback)=>options?.all?callback(null,[{address:request.serverAddress,family:isIP(request.serverAddress)}]):callback(null,request.serverAddress,isIP(request.serverAddress))},response=>{const chunks=[];let total=0;response.on("data",chunk=>{total+=chunk.length;if(total>64*1024*1024){req.destroy(new Error("EGRESS_RESPONSE_LIMIT"));return;}chunks.push(chunk)});response.on("end",()=>resolve({status:response.statusCode,headers:{location:response.headers.location??null},bytes:Buffer.concat(chunks)}));});req.setTimeout(30_000,()=>req.destroy(new Error("EGRESS_TIMEOUT")));req.on("error",reject);req.end();})}};}

export async function fetchVerifiedToolchain(lock,io){const rows=validateToolchainLock(lock);if(typeof io?.resolve!=="function"||typeof io?.fetch!=="function")fail("EGRESS_BOUNDARY_REQUIRED");const destinations=[];const artifacts=[];for(const row of rows){const url=new URL(row.url);const addresses=await io.resolve(url.hostname);if(!Array.isArray(addresses)||addresses.length===0||addresses.some(ip=>!isPublicAddress(ip)))fail("EGRESS_ADDRESS_REFUSED");const ip=addresses[0];const response=await io.fetch({url:row.url,hostname:url.hostname,serverAddress:ip,port:443,followRedirects:false,sni:url.hostname,certificateHostname:url.hostname});if(response?.status>=300&&response?.status<400||response?.headers?.location)fail("EGRESS_REDIRECT_REFUSED");if(response?.status!==200||!Buffer.isBuffer(response.bytes))fail("EGRESS_FETCH_FAILED");const [algorithm,expected]=row.integrity.split("-",2);const actual=createHash(algorithm).update(response.bytes).digest("base64");if(actual!==expected)fail("INTEGRITY_MISMATCH");destinations.push(Object.freeze({hostname:url.hostname,ip,port:443,redirects:0}));const artifact=Object.freeze({path:row.path,url:row.url,integrity:row.integrity,bytes:response.bytes.length,digest:createHash("sha256").update(response.bytes).digest("hex")});await io.store?.(row,response.bytes,artifact);artifacts.push(artifact);}return Object.freeze({destinations,artifacts});}

async function main(){const[, ,lockPath,directory,receiptPath]=process.argv;if(!lockPath||!directory||!receiptPath)fail("PREPARATION_ARGUMENTS_REQUIRED");const lock=JSON.parse(await readFile(lockPath,"utf8"));const receipt=await prepareTarballDirectory(lock,directory,createPinnedHttpsIO());await writeFile(receiptPath,JSON.stringify(receipt,null,2)+"\n",{mode:0o400,flag:"wx"});}
if(process.argv[1]&&new URL(import.meta.url).pathname===process.argv[1])main().catch(error=>{process.stderr.write(`${String(error?.message??"PREPARATION_FAILED")}\n`);process.exitCode=1;});
