import { mkdir, writeFile, readFile, readdir, symlink } from "node:fs/promises";
import { dirname, join } from "node:path";
import { spawn } from "node:child_process";
import { decodeSnapshotBundle } from "../aca-controller/snapshot.mjs";
export const CHECK_PLANS=Object.freeze({
 unit:Object.freeze([{id:"unit-vitest",label:"Vitest unit suite",executable:"/usr/local/bin/node",argv:["/verifier/node_modules/vitest/vitest.mjs","run","--configLoader","runner","--config","/verifier/vitest.config.mjs","--root","/work","--exclude","src/phase8Journey.test.ts"]}]),
 build:Object.freeze([{id:"build-typescript",label:"TypeScript noEmit",executable:"/usr/local/bin/node",argv:["/verifier/node_modules/typescript/bin/tsc","--noEmit","--project","/verifier/tsconfig.json"]},{id:"build-vite",label:"Vite bundle",executable:"/usr/local/bin/node",argv:["/verifier/node_modules/vite/bin/vite.js","build","--configLoader","runner","--config","/verifier/vite.config.mjs"]}])
});
export async function probeIsolation(input){const value=input??{uid:process.getuid?.(),gid:process.getgid?.(),status:await readFile("/proc/self/status","utf8"),mounts:await readFile("/proc/mounts","utf8"),interfaces:await readdir("/sys/class/net"),routes:(await readFile("/proc/net/route","utf8")).trim().split("\n").slice(1).map(row=>row.trim().split(/\s+/)[0]),env:{...process.env}};const expectedEnv=["ACA_CHECK_ID","CI","HOME","HOSTNAME","LANG","LC_ALL","PATH"].sort();const actualEnv=Object.keys(value.env).sort();const caps=["CapInh","CapPrm","CapEff","CapBnd","CapAmb"];if(value.uid!==65532||value.gid!==65532||!caps.every(name=>new RegExp(`^${name}:\\s*0{16}$`,`m`).test(value.status))||!/^NoNewPrivs:\s*1$/m.test(value.status)||!/^\S+ \/ \S+ ro(?:,| )/m.test(value.mounts)||!Array.isArray(value.interfaces)||value.interfaces.some(name=>name!=="lo")||!Array.isArray(value.routes)||value.routes.some(name=>name!=="lo")||JSON.stringify(actualEnv)!==JSON.stringify(expectedEnv)||!/^[0-9a-f]{12}$/.test(value.env.HOSTNAME)||value.env.HOME!=="/nonexistent"||value.env.PATH!=="/usr/local/bin:/usr/bin:/bin"||value.env.CI!=="1"||!["unit","build"].includes(value.env.ACA_CHECK_ID))throw new Error("ISOLATION_REFUSED");return Object.freeze({qualified:true,uid:value.uid,gid:value.gid,capabilities:"ZERO",noNewPrivileges:true,root:"READ_ONLY",network:"LOOPBACK_ONLY"});}
export async function materializeSnapshot(input,root="/work"){const bytes=Buffer.isBuffer(input)?input:await readFile(input);const decoded=decodeSnapshotBundle(bytes);for(const entry of decoded.entries){const target=join(root,...entry.path.split("/"));if(!target.startsWith(`${root}/`))throw new Error("SNAPSHOT_PATH_REFUSED");await mkdir(dirname(target),{recursive:true,mode:0o755});await writeFile(target,entry.content,{mode:entry.mode==="100755"?0o755:0o644,flag:"wx"});}return Object.freeze({entries:decoded.entries.length,snapshotDigest:decoded.snapshotDigest,bundleDigest:decoded.bundleDigest});}
export async function linkVerifierToolchain(root="/work",target="/verifier/node_modules"){await symlink(target,join(root,"node_modules"),"dir");}
const realSpawn=command=>new Promise(resolve=>{const child=spawn(command.executable,command.argv,{cwd:"/work",env:{HOME:"/nonexistent",PATH:"/usr/local/bin:/usr/bin:/bin",CI:"1",LANG:"C.UTF-8",LC_ALL:"C.UTF-8"},stdio:["ignore","inherit","inherit"]});child.once("error",()=>resolve({exitCode:null,signal:null,infrastructure:true}));child.once("exit",(exitCode,signal)=>resolve({exitCode,signal}));});
export async function runCheck(checkId,options={}){const plan=CHECK_PLANS[checkId];if(!plan)throw new Error("UNKNOWN_CHECK");const commands=[];for(const command of plan){const outcome=await(options.spawn??realSpawn)(command);commands.push(Object.freeze({id:command.id,label:command.label,...outcome}));if(outcome.infrastructure||outcome.signal!==null||outcome.exitCode!==0)return Object.freeze({checkId,state:outcome.infrastructure?"INDETERMINATE":"FAIL",commands});}return Object.freeze({checkId,state:"PASS",commands});}
async function main(){const snapshot=process.env.ACA_SNAPSHOT_PATH??"/sealed/snapshot.bin";const check=process.env.ACA_CHECK_ID;await probeIsolation();await materializeSnapshot(snapshot,"/work");await linkVerifierToolchain();const result=await runCheck(check);process.stderr.write(`\nACA_RUNNER_RESULT ${JSON.stringify(result)}\n`);process.exitCode=result.state==="PASS"?0:result.state==="FAIL"?1:2;}
if(process.argv[1]&&new URL(import.meta.url).pathname===process.argv[1])main().catch(error=>{process.stderr.write(`ACA_RUNNER_INFRASTRUCTURE ${String(error?.message??"FAILED")}\n`);process.exitCode=2;});
